# @author Ivan Senic
# @author Saurabh Verma
name: Release Workflow

# runs on
# * pushing new tag with 'v' prefix
# * manual trigger
on: push

# global env vars, available in all jobs and steps
env:
  MAVEN_OPTS: '-Xmx4g'

jobs:

  # creates a PR for bumping the versions to the next snapshot
  # only executed if we have created the new release
  create-pr:
    name: Version upgrade PR
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Generate changelog
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./update_changelog.sh

